# Variables and Placeholders

During optimization Tensorflow tunes the parameters of the model.  

**Variables** can hold the values of weights and biases throughout the session.  

**Variables** need to be initialized.

**Placeholders** are initially empty, however they do need a declared expected datatype with an optional shape argument.

In [2]:
import tensorflow as tf

In [3]:
import numpy as np

In [4]:
tensor_1d = np.array([1.45, -1, 0.2, 102.1])

In [5]:
type(tensor_1d)

numpy.ndarray

In [6]:
tensor = tf.convert_to_tensor(tensor_1d, dtype=tf.float64)

In [7]:
tensor

<tf.Tensor 'Const:0' shape=(4,) dtype=float64>

In [8]:
sess = tf.Session()

In [9]:
print (sess.run(tensor))

[  1.45  -1.     0.2  102.1 ]


In [10]:
print ( sess.run(tensor[0]))

1.45


In [19]:
tensor_2d = np.array(np.random.rand(4, 4), dtype='float32')

In [20]:
tensor_2d 

array([[0.42748398, 0.6244521 , 0.5032342 , 0.19563921],
       [0.10827295, 0.3606957 , 0.7924058 , 0.7749681 ],
       [0.19856869, 0.5944855 , 0.76049346, 0.745529  ],
       [0.2698493 , 0.9576355 , 0.8556652 , 0.14388736]], dtype=float32)

In [21]:
tensor_2d_1 = np.array(np.random.rand(4, 4), dtype='float32')

In [22]:
tensor_2d_1

array([[0.93707454, 0.82924783, 0.90954345, 0.6603781 ],
       [0.14031607, 0.8760928 , 0.43546417, 0.9137475 ],
       [0.590876  , 0.39023238, 0.88859487, 0.13363673],
       [0.8816331 , 0.75944567, 0.93786776, 0.38802728]], dtype=float32)

In [23]:
tensor_2d_2 = np.array(np.random.rand(4, 4), dtype='float32')

In [24]:
tensor_2d_2

array([[0.04569081, 0.3301538 , 0.9160836 , 0.95910454],
       [0.7374736 , 0.6330327 , 0.69402385, 0.0212449 ],
       [0.05439356, 0.31823722, 0.08121054, 0.45888168],
       [0.18956031, 0.1623097 , 0.08617251, 0.14577307]], dtype=float32)

In [25]:
m1 = tf.convert_to_tensor(tensor_2d)
m2 = tf.convert_to_tensor(tensor_2d_1)
m3 = tf.convert_to_tensor(tensor_2d_2)

In [29]:
mat_product = tf.matmul(m1, m2)

In [30]:
mat_product

<tf.Tensor 'MatMul:0' shape=(4, 4) dtype=float32>

In [31]:
mat_sum = tf.add(m2, m3)

In [32]:
mat_det = tf.matrix_determinant(m3)

In [33]:
print (sess.run(mat_product))

[[0.95803607 1.2465239  1.2913969  0.99605656]
 [1.3035223  1.3035566  1.6864944  0.8076892 ]
 [1.3761299  1.5484451  1.8144622  1.0652555 ]
 [1.0196885  1.5059323  1.5577426  1.2234201 ]]


In [34]:
print (sess.run(mat_det))

0.03237913


### Variables

In [14]:
tensor_1 = tf.random_uniform(shape= (4,4),minval= 0,maxval= 1)

In [15]:
var = tf.Variable(initial_value= tensor_1)

In [16]:
print(var)

<tf.Variable 'Variable_1:0' shape=(4, 4) dtype=float32_ref>


#### All Global Variables MUST be initialized

In [17]:
init = tf.global_variables_initializer()

In [18]:
sess.run(init)

In [19]:
var.eval()

array([[0.9432347 , 0.71787226, 0.52662075, 0.878441  ],
       [0.8438418 , 0.31458127, 0.88203466, 0.02395511],
       [0.8797786 , 0.7799493 , 0.7688056 , 0.3309462 ],
       [0.7402564 , 0.5289711 , 0.36457193, 0.36033356]], dtype=float32)

In [20]:
sess.run(var)

array([[0.9432347 , 0.71787226, 0.52662075, 0.878441  ],
       [0.8438418 , 0.31458127, 0.88203466, 0.02395511],
       [0.8797786 , 0.7799493 , 0.7688056 , 0.3309462 ],
       [0.7402564 , 0.5289711 , 0.36457193, 0.36033356]], dtype=float32)

### Placeholders

In [21]:
ph = tf.placeholder(tf.float32)

In [22]:
ph = tf.placeholder(tf.int32)

**shape** argument is generally used as following

In [23]:
ph = tf.placeholder(tf.int32, shape = (None, 5))

Here, **None** can be overwritten by the **no of samples** of train data we have and **5** here is assumed to be the **no of features.**

#### Voila!